# fly.toml app configuration file generated for github-trendy on 2023-11-17T17:09:08+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "github-trendy"
primary_region = "arn"
kill_signal = "SIGINT"
kill_timeout = "5s"

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[build]
  builder = "paketobuildpacks/builder:base"
